image: ruby:2.1

before_script:
  - apt-get update -qq && apt-get install -y -qq wkhtmltopdf xvfb
pages:
  script:
  - gem install jekyll jekyll-gist redcarpet
  - jekyll build -d public/
  artifacts:
    paths:
    - public
  only:
  - gh-pages
